# Unified Application Configuration
application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true

logging:
  level: INFO
  format: json
  output: /var/log/app.log

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true

# Development configuration toggled via environment variable
development:
  enabled: false
  host: localhost
  port: 3000
  ssl_enabled: false
  hot_reload: false
  debug_mode: false
  mock_external_apis: false
  verbose_logging: false
